### YamlMime:Landing
title: Azure Arc 対応 Kubernetes
summary: Azure Arc を使用して Kubernetes クラスターを管理する方法について説明します
metadata:
  title: Azure Arc 対応 Kubernetes
  description: Azure でオンプレミスのマシンを管理する方法について説明します
  author: shashankbarsin
  ms.service: azure-arc
  ms.topic: landing-page
  ms.date: 03/02/2021
  ms.author: shasb
  ms.openlocfilehash: f97b1560e062d1849f726baff8cd66d8e75f8b7f
  ms.sourcegitcommit: b4647f06c0953435af3cb24baaf6d15a5a761a9c
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 03/02/2021
  ms.locfileid: "101647848"
landingContent:
- title: Azure Arc を使用して Kubernetes クラスターを Azure に接続する
  linkLists:
  - linkListType: overview
    links:
    - text: Azure Arc 対応 Kubernetes とは
      url: overview.md
    - text: Azure Arc 検証プログラム
      url: validation-program.md
  - linkListType: concept
    links:
    - text: エージェントのアーキテクチャ
      url: conceptual-agent-architecture.md
    - text: 構成と GitOps
      url: conceptual-configurations.md
    - text: よく寄せられる質問
      url: faq.md
- title: 作業開始
  linkLists:
  - linkListType: quickstart
    links:
    - text: Azure Arc にクラスターを接続する
      url: quickstart-connect-cluster.md
- title: GitOps を使用して構成をデプロイする
  linkLists:
  - linkListType: tutorial
    links:
    - text: GitOps を使用して構成をデプロイする
      url: tutorial-use-gitops-connected-cluster.md
- title: クラスタの構成、管理、監視
  linkLists:
  - linkListType: how-to-guide
    links:
    - text: GitOps を使用して Helm グラフをデプロイする
      url: use-gitops-with-helm.md
    - text: Azure Policy を使用して GitOps を適用する
      url: use-azure-policy.md
    - text: Azure IoT Edge ワークロードをデプロイする
      url: deploy-azure-iot-edge-workloads.md
- title: 概念実証
  linkLists:
  - linkListType: sample
    links:
    - text: ジャンプスタート
      url: https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_k8s/
- title: 参照アーキテクチャ
  linkLists:
  - linkListType: architecture
    links:
    - text: ハイブリッド Kubernetes クラスターのデプロイと構成を管理する
      url: /azure/architecture/hybrid/arc-hybrid-kubernetes
